.TH MACRODEVICE-LUA 1
.SH NAME
macrodevice-lua \- turn any input device into a dedicated macrodevice
.SH SYNOPSIS
.B macrodevice-lua
[\fB\-f\fR] [\fB\-a\fR \fIARGUMENT\fR] \fB\-c\fR \fIFILE\fR
.br
.B macrodevice-lua
\fB\-h\fR
.SH DESCRIPTION
Open an input device and call a lua script to execute commands when an event occurs.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print a help message.
.TP
\fB\-c\fR, \fB\-\-config\fR=\fIFILE\fR
The lua or fennel script that should be loaded.
.TP
\fB-l\fR, \fB\-\-language\fR=\fILANGUAGE\fR
The language of the config file. Supported are 'lua', 'fennel', 'auto' (the file extension is used to determine the language).
.TP
\fB\-f\fR, \fB\-\-fork\fR
Fork into the background.
.TP
\fB\-a\fR, \fB\-\-arg=\fIARGUMENT\fR
Add \fIARGUMENT\fR to the macrodevice.arg table. Can be used multiple times.
.SH EXAMPLES
Start and run in the background
.PP
.nf
.RS
macrodevice-lua -f -c your-config.lua
.RE
.fi
.PP
.SH FILES
Examples and the backend documentation can be found in \fI/usr/share/doc/macrodevice\fR.
.SH COPYRIGHT
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version.
